### ISSUE TITLE
Unnecessary escaping backslash within github wikipage links

### ISSUE THREAD

**Issue by devfoo-one** [shurcooL/atom-markdown-format#15]
Since version 2.5.0 i´m having issues with [github-style wiki links](https://help.github.com/articles/adding-links-to-wikis/#using-a-wiki-markup-syntax-to-make-links). Referencing another wikipage on github is done like this:

`[[NodeJS|nodejs]]`

but v2.5.0 adds an unnecessary backslash to this line

`\[[NodeJS|nodejs]]`

**Comment by shurcooL** [comment]
I am now deprecating this entire package because I do not have enough resources to make it's user experience good enough and thus worthy of existing. Please see https://github.com/shurcooL/atom-markdown-format/pull/26 for full details and rationale. Because of that, I will close this issue.
