### ISSUE TITLE
Add support for GFM Tables

### ISSUE THREAD

**Issue by bradharms** [shurcooL/atom-markdown-format#23]
I like what this does, but I can't use it because it completely destroys my Github-flavored Markdown tables. It would be cool if it could detect and format tables and pad cells with spaces and add appropriate dashes to the header.

**Comment by shurcooL** [comment]
It already supports GFM tables, and formats them to be nicely aligned.

For example, try this table:

```
Markdown | Less | Pretty
--- | --- | ---
*Still* | `renders` | **nicely**
1 | 2 | 3
```

After saving, it should become:

```
| Markdown | Less      | Pretty     |
|----------|-----------|------------|
| *Still*  | `renders` | **nicely** |
| 1        | 2         | 3          |
```

What input did you try it on and saw it fail?

**Comment by bradharms** [comment]
I tried this:

    | a | b |
    |-|-|
    | c | d |

which resulted in this:

| a | b | |-|-| | c | d |

however I just found out it will work if I add at least 2 more hyphens below the headers.

**Comment by shurcooL** [comment]
That seems consistent with GitHub rendering of tables, is it not?

**Comment by bradharms** [comment]
Well, yes. I guess I just never noticed until now. Sorry! :+1:

**Comment by shurcooL** [comment]
No problem. Closing since this feature is already implemented. :)
