### ISSUE TITLE
Code block 

### ISSUE THREAD

**Issue by marcosmolla** [shurcooL/atom-markdown-format#33]
Hi!

When using
```
```julia 
Pkg.add("Rmath")
Pkg.build("Rmath")```
```

it changes to 

```
`julia 
Pkg.add("Rmath")
Pkg.build("Rmath")`
```

when saving, which deletes all the nice highlighting. 
Any idea how to avoid this?
Best wishes!

**Comment by dmitshur** [comment]
Hi,

To correctly use a fenced code block, the closing backticks need to start on a new line, like so:

    ```julia 
    Pkg.add("Rmath")
    Pkg.build("Rmath")
    ```

You can read more about fenced code blocks at https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks. Hope that helps!

**Comment by marcosmolla** [comment]
Oh thanks! That's it!!
