### ISSUE TITLE
Make trigger on save a setting

### ISSUE THREAD

**Issue by exalted** [shurcooL/atom-markdown-format#6]
It is certainly useful to auto trigger formatting on save, but some people may want to trigger it via keyboard shortcuts rather whenever they want to, instead of on each save.

So, I am proposing a setting where optionally we could set a keyboard shortcut, as well as being able to disable auto trigger on save.

**Comment by shurcooL** [comment]
I am now deprecating this entire package because I do not have enough resources to make it's user experience good enough and thus worthy of existing. Please see https://github.com/shurcooL/atom-markdown-format/pull/26 for full details and rationale. Because of that, I will close this issue.
